before:
  hooks:
    - go mod tidy
builds:
  - binary: easy-params
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/technicallyjosh/easy-params/cmd.version={{ .Version }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: technicallyjosh
      name: homebrew-easy-params
    description: Opinionated CLI for easy management of SSM Parameters.
    homepage: https://github.com/technicallyjosh/easy-params
    test: |
      system "#{bin}/easy-params --version"
