before:
  hooks:
    - go mod tidy
builds:
  - binary: ezparams
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - github:
      owner: technicallyjosh
      name: homebrew-easy-params
    description: Opinionated CLI for easy management of SSM Parameters.
    homepage: https://github.com/technicallyjosh/easy-params
    test: |
      system "#{bin}/ezparams --version"
